### ISSUE TITLE
[Plugin conflict] Soft WSoD when disabling/enabling "All Products for WooCommerce Subscriptions"

### ISSUE THREAD

**Issue by lqdforce** [lukecav/performance-improvements-for-woocommerce#4]
## Description
unable to update/disable/enable official woocommerce.com plugin "All Products for WooCommerce Subscriptions".

## Expected Behavior
Ability to update/disable/activate all official plugins when PIW plugin is active.

## Actual Behavior
wordpress plugins page throws WSoD with no error, log is clear too. 
When PIW is activated, cannot update/disable/enable the plugin mentioned above.

## Possible Fix
Not a fix, but a workaround. deactivate PIW, carry out plugin maintenance and reactivate PIW.

## Steps to Reproduce
https://woocommerce.com/products/all-products-for-woocommerce-subscriptions/

1. install and activate PIW plugin.
2. install "All Products for WooCommerce Subscriptions" either from file, ftp or from woocommerce.com
3.  try to activate or deactivate the plugin above, while PIW is installed and activated.
4. temporary WSoD (client side), can still go back to wp-admin. plugin remains unchanged.

## Context
Unable to carry official woocommerce.com plugin maintenance while using PIW.
It's been like this for a long while. across older WP,WC / WCS / WCSAP versions, everything. 
afaik it goes back to PIW  1.0.4 and/or "All Products for WooCommerce Subscriptions" 2.1.5

## Your Environment

Wordpress 5.4.2
WooCommerce 4.3.0
WooCommerce Subscriptions 3.0.5
WooCommerce All Products For Subscriptions 3.1.15
Performance Improvements for WooCommerce 1.1.0
--
Chromium 86.0.4185.0 64-bit
Win10 x64 Desktop

**Comment by lukecav** [comment]
I do not have a current version of WooCommerce Subscriptions and All Products for WooCommerce Subscriptions to test against.

**Comment by lqdforce** [comment]
@lukecav closed as wontfix then edited to testing ? I'm confused.
Have you managed to test this setup? I can provide a test server, or the plugin zips.

I updated to the 1.1.1 PIW and also to the newest APWCS plugin, same issue remains.

**Comment by lukecav** [comment]
@lqdforce Again not sure which filter would cause plugins on WooCommerce.com not to be able to be updated.

**Comment by lqdforce** [comment]
@lukecav update plugin is another thing. the main issue is when I deactivate that plugin (WooCommerce All Products For Subscriptions)  and when PIW is active. instant WSOD.

well, at least this plugin conflict is logged here for others who may experience similar issues.

**Comment by lukecav** [comment]
Why not deactivate PIW and keep WooCommerce All Products For Subscriptions plugin active if you are using it on the site. You can pull out the needed code snippets for WooCommerce performance and put them into your own custom plugin.

**Comment by lukecav** [comment]
`Deprecated: add_option_whitelist is deprecated since version 5.5.0! Use add_allowed_options() instead. in /chroot/home/a8a478eb/storebuilder.com/html/wp-includes/functions.php on line 4773 Fatal error: Uncaught Exception: Invalid data store. in /chroot/home/a8a478eb/storebuilder.com/html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php:107 Stack trace: #0 /chroot/home/a8a478eb/storebuilder.com/html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(139): WC_Data_Store->__construct('admin') #1 /chroot/home/a8a478eb/storebuilder.com/html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/WC_Admin_Notes.php(111): WC_Data_Store::load('admin-note') #2 /chroot/home/a8a478eb/storebuilder.com/html/wp-content/plugins/woocommerce-all-products-for-subscriptions/woocommerce-all-products-for-subscriptions.php(360): Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes::delete_notes_with_name(Array) #3 /chroot/home/a8a478eb/storebuilder.com/html/wp-content/plugins/woocommerce-all-products-for-subscriptions/woocommerce-all-products-for-subscriptions.php(421): WCS_ATT->deactivate() #4 /chroot/home/a8a478eb/storebuilder.com/html/wp-includes/class-wp-hook.php(287): deactivate_wcs_att( in /chroot/home/a8a478eb/storebuilder.com/html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php on line 107`

**Comment by lukecav** [comment]
Looks like the issue is due to the WooCommerce Admin being disabled using these lines in the plugin.

https://github.com/lukecav/performance-improvements-for-woocommerce/blob/main/wc-performance-improvements.php#L81-L82

```
// Disable the WooCommerce Admin
add_filter( 'woocommerce_admin_disabled', '__return_true' );
```
